# :maple_leaf:错误与异常处理

<p id="title"></p>

## 目录点击链接
:point_right:<a href="#one" >1捕获异常<a><br>


 ***
<p id = "one"></p>  
  
## :four_leaf_clover:捕获异常 ##

使用try,catch,finally来捕获异常

* try块包含的代码组成了程序的正常操作部分，但这部分程序可能会有错误

* catch块包含的代码为处理各种错误的情况，这些错误是try中处理代码遇到的。

* finally块包含的代码清理资源或执行通常要在try块或catch块尾执行，无论是否有异常都要执行这个块

### 执行步骤 ###

(1)执行流程进入try块

(2)如果try中没有错误直接到达try尾部，如果有finally执行该块，一旦有错误，则try中程序会终止到达catch块，然后处理错误后再转到finally块

(3)在catch中处理错误

(4)执行catch不同的错误类型

(5)finally存在则执行该块

### 运行示例 ###

下面的示例是对用户输入的数字0~1000进行校检，针对错误进行的处理
```C#
            int k = 3;
            bool falg = true;
            while(falg)
            {
                if(k==0)falg = false;
                try{
                    string s;
                    Console.WriteLine("please input data:");
                    s = Console.ReadLine();
                    //是否为空
                    if(string.IsNullOrEmpty(s))
                    {
                        break;
                    }
                    //转换类型
                    int index = Convert.ToInt32(s);
      
                    if(index<0||index>1000)
                    {
                        //针对越界声明异常类型
                        throw new IndexOutOfRangeException($"你输入的数字:{s}越界(0~1000)");
                    }

                    Console.WriteLine($"你输入的数字: {index}");
                }
                //针对数字越界的错误执行的处理
                catch(IndexOutOfRangeException ex)
                {
                    Console.WriteLine(ex.Message);
                }
                //其余的错误处理
                catch(Exception ex)
                {
                    Console.WriteLine($"{ex.Message}");
                }
                finally
                {
                    Console.WriteLine("结束!");
                }
                k--;
            }
```

一开始程序进入try中如果一旦为空，break语句不止退出try块，还会退出while循环。 throw new IndexOutOfRangeException()是一个定义的异常类的构造函数该类
的参数为一个错误文本，所以下面catch中IndexOutOfRangeException ex是指try中对于这个index<0||index>1000不满足的错误返回的对象，Message是错误描述的
属性，如果错误不是由于我们规定的条件则返回的是Exception ex，它的Message属性是错误的原因，这个就不能是自己写的错误原因，而是返回系统编译的原因。

编译结果：

	please input data:
	256
	你输入的数字: 256
	结束!
	please input data:
	1556
	你输入的数字:1556越界(0~1000)
	结束!
	please input data:
	akfka
	Input string was not in a correct format.
	结束!
	
 


